# File: .github/workflows/generate-installer.yml
name: Generate macOS Installer

on:
  workflow_dispatch:
    inputs:
      macos_version:
        type: choice
        description: "macOS Version"
        required: true
        options:
          - Sequoia v15.3.1
          - Sonoma v14.7.4
          - Ventura v13.7.4
          - Monterey v12.7.4
      file:
        type: choice
        description: "File Type"
        required: true
        options:
          - ISO
          - DMG
          - ZIP

run-name: Generate macOS Installer - ${{ github.event.inputs.macos_version }} ${{ github.event.inputs.file }}

env:
  installer_version: "" # Do not touch: Populated by extract-details (suppresses warnings)
  installer_name: "" # Do not touch: Populated by extract-details (suppresses warnings)

jobs:
  build:
    runs-on: macos-latest
    if: github.repository == 'MeeUuuu/Download-macOS'
    steps:
      - uses: actions/checkout@v4
      
      # Setup
      - name: Extract Version Details
        id: extract-details
        run: |
          string="${{ github.event.inputs.macos_version }}"
          echo "installer_version=${string//*v/}" >> $GITHUB_ENV
          echo "installer_name=${string// v*/}" >> $GITHUB_ENV

      # Download Installer
      - name: Download macOS Installer
        run: |
          softwareupdate --fetch-full-installer --full-installer-version ${{ env.installer_version }}

      # Generate Installer
      - if: github.event.inputs.file == 'dmg'
        name: Generate macOS DMG Installer
        run: |
          # 增大磁盘映像至17.5GB并清理空间
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 17500m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 15
          # 使用官方工具创建安装介质
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction
          hdiutil eject -force /Volumes/'Install macOS ${{ env.installer_name }}'
          sudo mv /tmp/'${{ env.installer_name }}'.dmg ~/Desktop/'${{ env.installer_name }}'.dmg

      - if: github.event.inputs.file == 'iso'
        name: Generate macOS ISO Installer
        run: |
          # 增大磁盘映像至18GB
          sudo hdiutil create -o /tmp/'${{ env.installer_name }}' -size 18000m -volname '${{ env.installer_name }}' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/'${{ env.installer_name }}'.dmg -noverify -mountpoint /Volumes/'${{ env.installer_name }}'
          sleep 20
          # 使用官方工具并延长等待时间
          sudo /Applications/'Install macOS ${{ env.installer_name }}'.app/Contents/Resources/createinstallmedia --volume /Volumes/'${{ env.installer_name }}' --nointeraction
          echo "等待安装程序完成（最长300秒）..."
          for i in {1..30}; do
              sleep 10
              if ! pgrep -q "createinstallmedia"; then break; fi
          done
          hdiutil eject -force /Volumes/'Install macOS ${{ env.installer_name }}'
          hdiutil convert /tmp/'${{ env.installer_name }}'.dmg -format UDTO -o ~/Desktop/'${{ env.installer_name }}'
          mv -v ~/Desktop/'${{ env.installer_name }}'.cdr ~/Desktop/'${{ env.installer_name }}'.iso
          sudo rm -fv /tmp/'${{ env.installer_name }}'.dmg

      - if: github.event.inputs.file == 'zip'
        name: Generate macOS ZIP Installer
        run: |
          cd /Applications
          zip -r 'Install macOS ${{ env.installer_name }}.zip' 'Install macOS ${{ env.installer_name }}.app'
          mv -v 'Install macOS ${{ env.installer_name }}.zip' ~/Desktop/'${{ env.installer_name }}.zip'

      # Upload Installer
      - name: Upload ${{ github.event.inputs.file }}
        uses: actions/upload-artifact@v4
        with:
          name: macOS ${{ env.installer_name }}
          path: "~/Desktop/${{ env.installer_name }}.${{ github.event.inputs.file }}"
